### ISSUE TITLE
NUID generated Id seems guessable

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/jnats#12]
Larry,

I used one of the classes NUID from snapshot to generate UUID. As per jnats code this is how it is used. I did the same thing:

`NUID.nextGlobal()
`
However when I did the same thing in all the places UUID is needed I found that generated Ids are somewhat guessable. This is the result of consecutive runs:

```
eoy2yjf5z47ye5g32qj3p3
eoy2yjf5z47ye5g32qj3qn
eoy2yjf5z47ye5g32qj3s7
eoy2yjf5z47ye5g32qj3tr
eoy2yjf5z47ye5g32qj3vb

```
If you see first 20 chars are same. If this an expected output?

thanks,

Sachin

**Comment by mcqueary** [comment]
No, the prefix length should be 12, and only those should be the same. Thanks for bringing this to my attention; although i tested for uniqueness, I didn't test for this.

**Comment by mcqueary** [comment]
@sachinwalia2k8 On further thought, this functions as intended. Each NUID is a base36 string 22 characters in length, with fixed prefix of 12 characters generated from a SecureRandom using SHA1PRNG, and the last 10 characters being an incremental sequence. The increment is a (pseudo-)random number between 33 and 333, and is fixed for each instance of NUID. Considering that the generated strings are base36, and 36^2 is 1296, you will see roughly 3 (~1296/333) to 39 (~1296/33) NUID strings in a row that share the same least-significant 2 bytes.

If you have concerns about the predictability of sequential NUID strings, the solution would be to simply construct a fresh NUID instance as frequently as you deem necessary, rather than generating from the global NUID. While this will be less entropy-friendly, it will certainly be less predictable, as the entire string including its increment would change periodically.

**Comment by sachinwalia2k8** [comment]
Thanks Larry. let me try that and update this ticket.

**Comment by sachinwalia2k8** [comment]
Larry your explanation makes sense. I tried the other approach with creating NUID instance on every request. It definitely gives far more randomized distribution. On testing the three different approach: Random UUID vs NUID on-demand vs NUID global there is definitely an advantage in going for generating via nextGlobal as this is best in performance followed by NUID on demand and slowest is UUID.randomUUID.
